app/models.py
from google.appengine.ext import db


class Admin(db.Model):
    email = db.EmailProperty(required=True)


class Faculty(db.Model):
    name = db.StringProperty(required=True)
    description = db.TextProperty(required=True)
    logo = db.BlobProperty(required=False)


class News(db.Model):
    faculty = db.ReferenceProperty(Faculty)
    name = db.StringProperty(required=True)
    body = db.TextProperty(required=True)
    image = db.BlobProperty(required=False)


class GroupsOfBlogs(db.Model):
    name = db.StringProperty(required=True)


class Blog(db.Model):
    name = db.StringProperty(required=True)
    content = db.StringProperty(required=True, multiline=True)
    group = db.ReferenceProperty(GroupsOfBlogs, required=True)
    date = db.DateTimeProperty(required=True, auto_now_add=True)

app/admin/forms.py
from flask.ext.wtf import Form
from wtforms import validators, StringField, TextAreaField


class AdminForm(Form):
    email = StringField(u"email", validators=[validators.DataRequired(message=u"Email is required"),
                                              validators.Email(message=u"Invalid email")])


class NewsForm(Form):
    name = StringField(u"name", validators=[validators.DataRequired(message=u"This field is required!")])
    body = TextAreaField(u"description", validators=[validators.DataRequired(u"This field is required!")])

app/__init__.py
# -*- coding: utf-8 -*-
import sys
import os

sys.path.insert(1, os.path.join(os.path.abspath('.'), 'env_faculty/lib/python2.7/site-packages'))

from flask import Flask

app = Flask(__name__)
app.config.from_object('settings')

import views
from app.admin.views import admin as AdminModule
app.register_blueprint(AdminModule)

app/admin/views.py
from flask import Blueprint, render_template, request, json, jsonify, abort
from app.decorators import *
from app.admin.forms import *
from app.models import Admin

admin = Blueprint('admin', __name__, url_prefix='/admin', template_folder='templates')


@admin.route('/', methods=['GET', 'POST'])
@only_admin
def admin_index():
    return render_template('admin-base.html', admins=Admin.all(), admin_form=AdminForm())


@admin.route('/add_admin', methods=['GET', 'POST'])
@only_admin
def add_admin():
    admin_form = AdminForm(request.form)
    key = ''
    if admin_form.validate():
        admin = Admin(email=admin_form.email.data)
        if Admin.all().count() >= 2:
            return json.dumps({'valid': False})
        admin.put()
        key = admin.key()
    return json.dumps({'valid': admin_form.validate_on_submit(), 'key': str(key), 'email': admin_form.email.data})


@admin.route('/news', methods=['GET', 'POST'])
@only_admin
def admin_news():
    return render_template('admin-news.html', news=News.all().get())


@admin.route('/delete_by_key/<string:key>', methods=['GET', 'POST'])
@only_admin
def delete_by_key(key):
    db.delete(key)
    return json.dumps({})


@admin.route('/add_faculty/')
@only_admin
def add_faculty():
    return render_template('admin-faculty.html')


@admin.route('/articles')
@only_admin
def articles():
    return render_template('admin-articles.html', blogs=db.Query(Blog).order("-date"), groups=GroupsOfBlogs.all())


@admin.route('/blog/group/<int:group_id>', methods=['POST'])
@only_admin
def blog_group_get(group_id):
    return jsonify(group=GroupsOfBlogs.get(group_id))


@admin.route('/blog/group/all', methods=['POST'])
@only_admin
def blog_group_get_all():
    return jsonify(groups=GroupsOfBlogs.get().all())


@admin.route('/blog/group/add', methods=['POST'])
@only_admin
def blog_group_add():
    data = json.loads(request.data)

    try:
        group = GroupsOfBlogs(name=data["name"])
    except (ValueError, KeyError, TypeError):
        return abort(400)

    group.put()

    return json.dumps({"key": group.key().id()})


@admin.route('/blog/group/<int:group_id>/edit', methods=['POST'])
@only_admin
def blog_group_edit(group_id):
    data = json.loads(request.data)
    group = GroupsOfBlogs.get_by_id(group_id)

    try:
        group.name = data["name"]
    except (ValueError, KeyError, TypeError):
        return abort(400)

    group.put()

    return json.dumps({})


@admin.route('/blog/group/<int:group_id>/delete', methods=['POST'])
@only_admin
def blog_group_delete(group_id):
    blogs_by_group = Blog.all().filter('group=', GroupsOfBlogs.get_by_id(long(group_id)))

    if blogs_by_group.count():
        return json.dumps({"msg": "Can't delete this group, because have blogs with that group"})

    group = GroupsOfBlogs.get_by_id(group_id)
    group.delete()

    return json.dumps({})


# page: admin/blog
@admin.route('/blog', methods=['GET'])
@only_admin
def blog():
    return render_template("admin-articles.html", blogs=db.Query(Blog).order("-date"), groups=GroupsOfBlogs.all())


@admin.route('/blog/<int:blog_id>', methods=['POST'])
@only_admin
def blog_get(blog_id):
    return jsonify(blog=Blog.get(blog_id))


@admin.route('/blog/<int:blog_id>/amount/<int:amount_blogs>')
@only_admin
def blog_get_certain_amount(blog_id, amount_blogs):
    return jsonify(blogs=Blog.all().order("-data").ancestor(blog_id).fetch(limit=amount_blogs))


@admin.route('/blog/add', methods=['POST'])
@only_admin
def blog_add():
    data = json.loads(request.data)

    Blog(name=data["name"], content=data["content"], group=GroupsOfBlogs.get_by_id(long(data["group"]))).put()

    return json.dumps({})


@admin.route('blog/<int:blog_id>/edit', methods=['POST'])
@only_admin
def blog_edit(blog_id):
    data = json.loads(request.data)
    blog = Blog.get_by_id(blog_id)

    try:
        blog.name = data["name"]
        blog.content = data["content"]
        blog.group = GroupsOfBlogs.get_by_id(long(data["group"]))

        blog.put()
    except (ValueError, KeyError, TypeError):
        return abort(400)

    return json.dumps({})


@admin.route('blog/<int:blog_id>/delete', methods=['POST'])
@only_admin
def blog_delete(blog_id):
    Blog.get_by_id(blog_id).delete()
    return json.dumps({})

app/views.py
from app import app
from flask import render_template, redirect, url_for
from models import *

PER_PAGE = 10


@app.route('/')
def index():
    return redirect(url_for('blog'))


@app.route('/faculty/', defaults={'page': 1, 'group': 0})
@app.route('/faculty/group/<int:group>', defaults={'page': 1})
@app.route('/faculty/page/<int:page>', defaults={'group': 0})
@app.route('/faculty/group/<int:group>/page/<int:page>')
def blog(group, page):
    from paginator import Paginator, InvalidPage, EmptyPage

    if group:
        model = Blog.all().filter('group = ', GroupsOfBlogs.get_by_id(group)).fetch(100)
    else:
        model = Blog.all().fetch(100)

    paginator = Paginator(model, 3)

    if page:
        try:
            page = int(page)
        except ValueError:
            page = 1
        try:
            paginator = paginator.page(page)
        except (EmptyPage, InvalidPage):
            paginator = paginator.page(paginator.num_pages)

    return render_template('base.html', group=group, paginator=paginator, current=page, groups=GroupsOfBlogs.all())


@app.route('/faculty/new/<int:id_group>')
def news(id_group):

    return render_template('news.html', xyu=Blog.get_by_id(id_group).content)

app/templates/admin-articles.html
{% extends "admin-base.html" %}

{% block head %}
    <link href="../static/blog/css/bootstrap-colorpicker.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/blog/css/admin_blog.css">
{% endblock %}

{% block content %}
    <div class="col-md-10">
        <div class="wrap">
            <div class="panel panel-own-full panel-transparent">
                <div class="panel-header">
                    <h1></h1>
                </div>
                <div class="panel-body">
                    <div class="blog-menu">
                        <div class="panel panel-blog-menu panel-blue">
                            <div class="panel-header">
                                <h2>Кафедры</h2>
                            </div>
                        </div>
                        <div class="panel panel-blog-menu panel-blue">
                            <div class="panel-header">
                                <h2>Добавить кафедру</h2>
                            </div>
                            <div class="panel-body">
                                <form id="form-group-add" class="form-group" action="{{ url_for('admin.blog_group_add') }}" method="post" fastform>
                                    <div class="form-group">
                                        <input name="name" type="text" class="form-control" placeholder="Название кафедры" required>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-default pull-right">Добавить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="panel panel-blog-menu panel-blue">
                            <div class="panel-body">
                                <form id="form-group-edit" class="form-group" method="post" fastform action-delete="{{ url_for('admin.blog_group_delete', group_id=0) }}" action-edit="{{ url_for('admin.blog_group_edit', group_id=0) }}">
                                    <div class="form-group">
                                        <select class="form-control" not-input select-group>
                                            {% for group in groups %}
                                                <option value="{{ group.key().id() }}" color="{{ group.color }}">{{ group.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <input name="name" type="text" class="form-control" placeholder="Название кафедры" required>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" action-name="delete" class="btn btn-default pull-left">Удалить</button>
                                        <button type="submit" action-name="edit" class="btn btn-default pull-right">Изменить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="panel panel-blog-menu panel-blue">
                            <div class="panel-header">
                                <h2>Посты</h2>
                            </div>
                        </div>
                        <div class="panel panel-blog-content panel-blue container-fluid">
                            <div class="panel-header">
                                <h2>Добавить пост</h2>
                            </div>
                            <div class="panel-body">
                                <form class="form-group" fastform action="{{ url_for('admin.blog_add') }}" method="post" id="form-blog-add">
                                    <div class="form-group">
                                        <input name="name" type="text" class="form-control" placeholder="Название поста" required>
                                    </div>
                                    <div class="form-group">
                                        <select name="group" class="form-control" select-group required>
                                            {% for group in groups %}
                                                <option value="{{ group.key().id() }}" color="{{ group.color }}">{{ group.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <textarea name="content" required></textarea>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-default pull-right">Добавить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        {% for blog in blogs %}
                            <div class="panel panel-blog-content panel-blue container-fluid" style="background-color: {{ blog.group.color }}">
                                <div class="panel-body">
                                    <form class="form-group" fastform action-edit="{{ url_for('admin.blog_edit', blog_id=blog.key().id()) }}" action-delete="{{ url_for('admin.blog_delete', blog_id=blog.key().id()) }}" method="post" id="form-blog-edit">
                                        <div class="form-group">
                                            <input name="name" type="text" class="form-control" placeholder="Название поста" required value="{{ blog.name }}">
                                        </div>
                                        <div class="form-group">
                                            <select name="group" class="form-control" select-group required>
                                                {% for group in groups %}
                                                    <option value="{{ group.key().id() }}" color="{{ group.color }}" {% if blog.group == group %}selected{% endif %}>{{ group.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <textarea name="content" required>{{ blog.content|safe }}</textarea>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" action-name="delete" class="btn btn-default pull-left">Удалить</button>
                                            <button type="submit" action-name="edit" class="btn btn-default pull-right">Изменить</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        {% endfor %}
                        {#<div class="row text-center">
                            <button type="button" class="btn btn-default" aria-label="Left Align">Загрузить еще</button>
                        </div>#}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="../static/blog/js/bootstrap-colorpicker.js"></script>
    <script src="../static/blog/ckeditor/ckeditor.js"></script>
    <script src="../static/blog/ckeditor/adapters/jquery.js"></script>
    <script src="../static/blog/js/fastforms.js"></script>
    <script src="../static/blog/js/script.js"></script>
{% endblock %}

app/templates/admin-base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <link rel="stylesheet" href="../static/css/bootstrap.css">
    <link rel="stylesheet" href="../static/css/bootstrap-theme.css">
    <link rel="stylesheet" href="../static/css/AdminStyle.css">
    <meta charset="UTF-8">
    <title>Admin panel</title>
    <script src="../static/js/jquery-1.11.2.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
<div clas="container">
    <div class="col-md-2 adminmenu">
        <div class="sidebar-nav">
            <div class="well menu">
                <ul class="nav nav-list">
                    <li class="nav-header"><a href="{{ url_for('admin.admin_index') }}" class="text-center">Admin Menu</a></li>
                {% block buttons %}
                {% endblock %}
                <img class="logo" width="100%" src="http://flask.pocoo.org/static/logo/flask.png" />
            </div>
        </div>
    </div>
    {% block content %}
        <div class="col-md-2">
            <form class="add-email">
                <div class="thumbnail text-center">
                    <div class="overlay-container">
                        <div class="form-group">
                            {{ admin_form.hidden_tag() }}
                            {{ admin_form.email(class="form-control", placeholder='Email only Google') }}
                            <br><div class="btn btn-success" onclick="AddEmail()">Add Admin</div>
                        </div>
                    </div>
                </div>
            </form>
            {% for admin in admins %}
                <div class="thumbnail text-center" id="{{ admin.key() }}">
                    <div class="overlay-container">
                        <p>Admin Email: {{ admin.email }}</p>
                        <div class="overlay-content">
                            <br><div class="btn btn-danger" onclick="DeleteByKey('{{ admin.key() }}')">Delete EMail</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock %}
</div>
{% block scripts %}
    <script>
        function AddEmail()
        {
            var data = new FormData($('.add-email')[0]);
            $.ajax({
                type: "POST",
                url: "add_admin",
                data: data,
                contentType: false,
                processData: false,
                dataType: "json",
                success: function (result){
                    if(result['valid'])
                    {
                        var deleteemail = 'DeleteByKey("'+result['key']+'")';
                        $('.add-email > .form-group').removeClass('has-error');
                        $('#email').val('');
                        var blockemail = "<div class='thumbnail text-center' id='" +result['key'] + "'>" +
                                "<div class=s'overlay-container'><p>Email: "+ result['email']+"</p><div class='overlay-content'><br>" +
                                "<div class='btn btn-danger' onclick='" +deleteemail+ "'>Delete Email" +
                                "</div></div></div></div>";
                        $(".add-email").after(blockemail);
                    }
                    else
                    {
                        $('#email').parent().addClass('has-error');
                    }
                }
            })

        }
        function DeleteByKey(key)
        {
            var url = "/admin/delete_by_key/"+key;
            $.ajax(
                    {
                        url : url,
                        type : "POST",
                        data :{},
                        contentType: false,
                        processData: false,
                        datatype: "JSON",
                        success: function()
                        {
                            document.getElementById(key).remove();
                        }
                    }
            )
        }
    </script>
{% endblock %}
</body>
</html>

app/templates/admin-faculty.html
{% extends "admin-base.html" %}
{% block content %}
{% endblock %}

app/templates/admin-news.html
{% extends "admin-base.html" %}
{% block content %}
{% for article in news %}
<div class="panel panel-blog-content panel-blue container-fluid">
                                <div class="panel-body">
                                    <form class="form-group">
                                        <div class="form-group">
                                            <input name="name" type="text" class="form-control" placeholder="Название поста" required value="{{ article.name }}">
                                        </div>
                                        <div class="form-group">
                                            <textarea name="content" required>{{ article.body|safe }}</textarea>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-default pull-left">Удалить</button>
                                            <button type="submit" class="btn btn-default pull-right">Изменить</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
            {% endfor %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en"> <!--<![endif]-->
<head>
    <title>Faculty Site</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico">

    <!-- CSS Global Compulsory -->
    <link rel="stylesheet" href="/static/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/css/style.css">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="/static/assets/plugins/line-icons/line-icons.css">
    <link rel="stylesheet" href="/static/assets/plugins/font-awesome/css/font-awesome.min.css">

    <!-- CSS Page Style -->
    <link rel="stylesheet" href="/static/assets/css/pages/blog.css">

    <!-- CSS Theme -->
    <link rel="stylesheet" href="/static/assets/css/themes/default.css" id="style_color">

    <!-- CSS Customization -->
    <link rel="stylesheet" href="/static/assets/css/custom.css">
</head>

<body>
<div class="wrapper">
    <!--=== Header ===-->
    <div class="header">
        <!-- Navbar -->
        <div class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-responsive-collapse">
                    <ul class="nav navbar-nav">
                        <!-- Home -->
                        <li class="active">
                            <a href="{{ url_for('index') }}" class="dropdown-toggle" data-toggle="dropdown">
                                Новости
                            </a>
                        </li>
                        <!-- End Home -->
                        <!-- Contacts -->
                        {% if groups.count() %}
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                Кафедры
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('blog') }}">Все</a></li>
                                {% for g in groups %}
                                <li><a href="{{ url_for('blog', group=g.key().id()) }}" {% if group == g.key().id() %}class="activate"{% endif %}>{{ g.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% endif %}
                        <!-- End Contacts -->
                    </ul>
                </div><!--/navbar-collapse-->
            </div>
        </div>
        <!-- End Navbar -->
    </div>
    <!--=== End Header ===-->

    <!--=== Content Part ===-->
    <div class="container content">
        <div class="row blog-page">
            <!-- Left Sidebar -->
            <div class="col-md-9 md-margin-bottom-40">
                <!--Blog Post-->

                {% if paginator.object_list %}
                        {% for blog in paginator.object_list %}
                <div class="row blog blog-medium margin-bottom-40">
                    <div class="col-md-5">
                        <img class="img-responsive" src="/static/assets/img/main/11.jpg" alt="">
                    </div>
                    <div class="col-md-7">
                        <h2>Заголовок {{ blog.name }}</h2>
                        <ul class="list-unstyled list-inline blog-info">
                            <li><i class="fa fa-calendar"></i>Дата написания {{ blog.date.strftime('%H:%M %d.%m.%Y') }}</li>
                            <li><i class="fa fa-tags"></i> Кафедра {{ blog.group.name }}</li>
                        </ul>
                        <p>

                        {{ blog.content|safe }}

                        <p><a class="btn-u btn-u-small" href="{{ url_for('news', id_group=blog.key().id()) }}"><i class="fa fa-location-arrow"></i> Читать больше</a>
                        </p>
                    </div>
                </div>
                <!--End Blog Post-->

                <hr class="margin-bottom-40">
                        {% endfor %}
                {% endif %}

                <!--End Blog Post-->

                <!--Pagination-->
                {% if paginator.has_previous() or paginator.has_next() %}
                    <div class="text-center">
                        <ul class="pagination">
                            {% if paginator.has_previous() %}
                                <li><a href="{{ url_for('blog', page=paginator.previous_page_number(), group=group) }}">«</a></li>
                            {% else %}
                                <span class="page-nulled">Previous</span>
                            {% endif %}
                            <span class="current" id="pagenum" title="{{ paginator.number }}">&nbsp;&nbsp;&nbsp;Page {{ paginator.number }} of {{ paginator.paginator.num_pages }}&nbsp;&nbsp;&nbsp;</span>
                            {% if paginator.has_next() %}
                                <li><a href="{{ url_for('blog', page=paginator.next_page_number(), group=group) }}">»</a></li>
                            {% else %}
                                <span class="page-nulled">Next</span>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
                <!--End Pagination-->
            </div>
            <!-- End Left Sidebar -->

            <!-- Right Sidebar -->
            <div class="col-md-3">

                <!-- Posts -->
                <div class="posts margin-bottom-40">
                    <div class="headline headline-md"><h2>Главы деканата</h2></div>
                    <dl class="dl-horizontal">
                        <dt><a href="#"><img src="http://www.kspu.edu/FileDownload.ashx/mini169x242_kuzmich.png?id=6686b370-76a1-4975-93b4-fc182f03e685" alt=""/></a></dt>
                        <dd>
                            <p><a href="#">Кузьмич В. И.</a></p>
                        </dd>
                    </dl>
                </div><!--/posts-->
                <!-- End Posts -->

            </div>
            <!-- End Right Sidebar -->
        </div><!--/row-->
    </div><!--/container-->
    <!--=== End Content Part ===-->

    <!--=== Footer ===-->
    <div class="footer" style="position:absolute;bottom:0">
        <div class="container">
            <div class="row">
            </div>
        </div>
    </div><!--/footer-->
    <!--=== End Footer ===-->

    <!--=== Copyright ===-->
    <div class="copyright" style="position:absolute;bottom:0;left:0;right:0">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>
                        2014 &copy; Unify. ALL Rights Reserved.
                        <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a>
                    </p>
                </div>
                <div class="col-md-6">
                    <a href="index.html">
                        <img class="pull-right" id="logo-footer" src="/static/assets/img/logo2-default.png" alt="">
                    </a>
                </div>
            </div>
        </div>
    </div><!--/copyright-->
    <!--=== End Copyright ===-->
</div><!--/wrapper-->

<!-- JS Global Compulsory -->
<script type="text/javascript" src="/static/assets/plugins/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="/static/assets/plugins/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="/static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<!-- JS Implementing Plugins -->
<script type="text/javascript" src="/static/assets/plugins/back-to-top.js"></script>
<!-- JS Page Level -->
<script type="text/javascript" src="/static/assets/js/app.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        App.init();
    });
</script>
<!--[if lt IE 9]>
<script src="assets/plugins/respond.js"></script>
<script src="assets/plugins/html5shiv.js"></script>
<![endif]-->
</body>
</html>